gender_list= [
    ('0', 'Male'),
    ('1', 'Female'),
]
religion_list = [
    ('0', 'Islam'),
    ('1', 'Hinduism'),
    ('2', 'Buddhism'),
    ('3', 'Christianity'),
    ('4', 'Others'),
]
marital_status_list = [
    ('0', 'Married'),
    ('1', 'Unmarried'),
]
designation_list = [
    ('0', 'Lecturer'),
    ('1','Senior Lecturer'),
    ('2', 'Professor'),
    ('3', 'Associate Professor'),
    ('4', 'Assistant Professor'),
    ('5', 'Coordinator'),
    ('6', 'Chairman'),
    ('7', 'Dean'),
]
# identity_mark_list = [
#     ('0', 'Lecturer'),
#     ('1','Senior Lecturer'),
#     ('2', 'Professor'),
#     ('3', 'Associate Professor'),
#     ('4', 'Assistant Professor'),
#     ('5', 'Coordinator'),
#     ('6', 'Chairman'),
#     ('7', 'Dean'),
# ]
complaint_type = [
    ('0', 'Harassment'),
    ('1', 'Service'),
    ('2', 'Staff'),
]
complaint_status = [
    ('0', 'Pending'),
    ('1', 'Accepted'),
    ('2', 'Rejected'),
    ('3', 'Closed'),
]
vehicle_color = [
    ('0', 'Red'),
    ('1', 'Green'),
    ('2', 'Yellow'),
    ('3', 'Black'),
    ('4', 'White'),
    ('5', 'Blue'),
    ('6', 'Ash'),
    ('7', 'Silver'),
]

vehicle_type = [
    ('0', 'Bus'),
    ('1', 'Mini Bus'),
    ('2', 'Micro Bus'),
    ('3', 'Private Car'),
    ('4', 'Covered Van'),
    ('5', 'Pickup'),
]
vehicle_status = [
    ('0', 'Running'),
    ('1', 'Repair'),
    ('2', 'New'),
    ('3', 'Broken'),
]

ticket_types = [
    ('1', 'Daily'),
    ('7', 'Weekly'),
    ('15', 'Fortnightly'),
    ('30', 'Monthly'),
    ('180', 'Half Yearly'),
    ('365', 'Yearly'),
]
ticket_status = [
    ('0', 'Pending'),
    ('1', 'Accepted'),
    ('2', 'Rejected'),
    ('3', 'Closed'),
]
payment_types = [
    ('0', 'Cash'),
]

complaint_feedback = [
    ('0', 'Excellent'),
    ('1', 'Satisfactory'),
    ('2', 'Above Average'),
    ('3', 'Average'),
    ('4', 'Below Average'),
    ('5', 'Poor'),
]
first_name_list = [
    'Rex',
    'Jackson',
    'Garth',
    'Karl',
    'Ivory',
    'Seth',
    'Marlin',
    'Blake',
    'Eliseo',
    'Lucius',
    'Allan',
    'David',
    'Joshua',
    'Kim',
    'Dennis',
    'Carter',
    'Lynn',
    'Stacy',
    'Clifford',
    'Elmo',
    'Toby',
    'Benito',
    'Mickey',
    'Fausto',
    'Hubert',
    'Buster',
    'Claude',
    'Sang',
    'Clyde',
    'Luther',
    'Kenton',
    'Jc',
    'Gayle',
    'Charles',
    'Anton',
    'Burton',
    'Claudio',
    'Glenn',
    'Ulysses',
    'Hilton',
    'Forrest',
    'Clint',
    'Billy',
    'Lucas',
    'Ivan',
    'Conrad',
    'Moses',
    'Sebastian',
    'Rudolph'
]

last_name_list = [
'Haga',
'Abbe',
'Rall',
'Dejesus',
'Cerrato',
'Yount',
'Odwyer',
'Byfield',
'Fuller',
'Gearheart',
'Gangestad',
'Keasey',
'Labella',
'Grace',
'Patel',
'Neuner',
'Charney',
'Kemp',
'Villavicencio',
'Dawe',
'Lank',
'Valverde',
'Verville',
'Mccurdy',
'Smalley'
'Borey',
'Oleary',
'Bushong',
'Stansbury',
'Colwell',
'Danziger',
'Ledlow',
'Erskine',
'Ekhoff',
'Yadon',
'Lindberg',
'Rohr',
'Blumstein',
'Bachman',
'Phillis',
'Millay',
'Cancel',
'Guizar',
'Mutchler',
'Arora',
'Talley',
'Kitts',
'Bayles',
'Bagg'
]
employee_id_list = [
'S-193',
'S-194',
'S-195',
'S-196',
'S-197',
'S-198',
'S-199',
'S-200',
'S-201',
'S-202',
'S-203',
'S-204',
'S-205',
'S-206',
'S-207',
'S-208',
'S-209',
'S-210',
'S-211',
'S-212',
]