# Generated by Django 2.2.6 on 2019-10-17 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('emergency_number', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField()),
                ('nid_number', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=200)),
                ('religion', models.CharField(choices=[('0', 'Islam'), ('1', 'Hinduism'), ('2', 'Buddhism'), ('3', 'Christianity'), ('4', 'Others')], max_length=200)),
                ('marital_status', models.CharField(choices=[('0', 'Married'), ('1', 'Unmarried')], max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
                ('updated_date', models.DateTimeField(max_length=200)),
                ('designation', models.CharField(choices=[('0', 'Lecturer'), ('1', 'Senior Lecturer'), ('2', 'Professor'), ('3', 'Associate Professor'), ('4', 'Assistant Professor'), ('5', 'Coordinator'), ('6', 'Chairman'), ('7', 'Dean')], max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('emergency_number', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField()),
                ('nid_number', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=200)),
                ('religion', models.CharField(choices=[('0', 'Islam'), ('1', 'Hinduism'), ('2', 'Buddhism'), ('3', 'Christianity'), ('4', 'Others')], max_length=200)),
                ('marital_status', models.CharField(choices=[('0', 'Married'), ('1', 'Unmarried')], max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
                ('updated_date', models.DateTimeField(max_length=200)),
                ('student_id', models.CharField(max_length=200, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
